name: Reciever of the release

on:
  issues:
    types: [created]

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 下载API文件
    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://api.github.com/repos/advancedfx/advancedfx/releases/latest
        # New filename to rename the downloaded file
        file-name: release.json
        #location: # optional, default is .

    # 运行工具
    - name: Run Repo-Tranporter
      run: |
        ls -al
        chmod 777 repo-transporter
        ./repo-transporter
        ls -al
    
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.6
      with:
        # Github Token with commit access
        github-token: $\{{ secrets.GITHUB_TOKEN }}

    - name: dir
      run: |
        ls -al
