name: Reciever of the release

on:
  schedule:
    - cron: "* * * * *"

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 下载API文件
    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://api.github.com/repos/advancedfx/advancedfx/releases/latest
        # New filename to rename the downloaded file
        file-name: release.json
        #location: # optional, default is .

    # 运行工具
    - name: Run Repo-Tranporter
      run: |
        ls -al
        chmod 777 repo-transporter
        ./repo-transporter
        ls -al
        
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        commit-message: 'Automatically pushed by GitHub Actions'
        rebase: 'true' # pull abd rebase before commit
        force-add: 'true'
        name: GitHub-Actions
        email: noreply@email.com 
    
    - name: dir
      run: |
        ls -al
        
    # 等待10s 以防先发布再push
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

  release:
    needs: transport
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 获取原仓库的版本
      - name: Get Latest HLAE Tag
      # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
        uses: actions-hub/watch-tag@master
        with:
          provider: github
          repository: advancedfx/advancedfx
          env_name: LATEST_HLAE_TAG
      
      - name: dir
        run: |
          ls -al
      
      # Release 发布
      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: 'v${{ env.LATEST_HLAE_TAG }}'
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: This release is automatically made by GitHub Actions
          draft: false
          prerelease: false
