name: Reciever of the release

on:
  repository_dispatch:
    types: [hlae_update_again]

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # 获取原仓库的版本
    - name: Get Latest HLAE Tag
      # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
      uses: actions-hub/watch-tag@master
      with:
         provider: github
         repository: advancedfx/advancedfx
         env_name: LATEST_HLAE_TAG
    
    # 下载API文件
    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://api.github.com/repos/advancedfx/advancedfx/releases
        # New filename to rename the downloaded file
        file-name: release.json
        #location: # optional, default is .

    ## 下载附件
    #- name: Download Release Asset
    #uses: fabriciobastian/download-release-asset-action@v1.0.6
    #with:
    #    # A specific release version. Defaults to latest
    #    version: # default is latest
    #    # Relative path to the repository in the format user/repo e.g.: myuser/my-repository
    #    repository: advancedfx/advancedfx
    #    # The name of the asset to download from the release
    #    file: 
    #    # Path to the directory where to download the asset
    #    out: ./'v${{ env.LATEST_HLAE_TAG }}'
    #    # The GitHub access token
    #    token: # optional, default is 

    - name: create directory
      run: mkdir ./v${{ env.LATEST_HLAE_TAG }}
    
    - name: release-downloader
      uses: robinraju/release-downloader@v1
      env: 
        DIR: './v${{ env.LATEST_HLAE_TAG }}'
      with:
        # The source repository path. Expected format {owner}/{repo}
        repository: advancedfx/advancedfx
        # A flag to choose between latest release and remaining releases
        latest: true
        out-file-path: ${{ env.DIR }}
    
    # commit 提交改动
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        # Commit message
        commit_message: "Git Auto Commit"

    # Push 上传
    - uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.GITHUB_TOKEN }}

    # Release 发布
    - name: Create a Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: 'v${{ env.LATEST_HLAE_TAG }}'
      with:
       tag_name: ${{ env.TAG }}
       release_name: ${{ env.TAG }}
       body: This release is automatically made by GitHub Actions
       draft: false
       prerelease: false
