name: make new release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 获取原仓库的版本
      - name: Get Latest HLAE Tag
      # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
        uses: actions-hub/watch-tag@master
        with:
          provider: github
          repository: advancedfx/advancedfx
          env_name: LATEST_HLAE_TAG
    
      # 运行工具
      - name: dir
        run: |
          ls -al
        
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
        
      # Release 发布
      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: 'v${{ env.LATEST_HLAE_TAG }}'
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: This release is automatically made by GitHub Actions
          draft: false
          prerelease: false
